#cloud-config
packages:
  - docker.io
  - kubectl
  - kubeadm
  - kubelet

runcmd:
  - kubeadm init --pod-network-cidr=10.244.0.0/16
  - mkdir -p $HOME/.kube
  - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  - kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
